# Sample partial deployment specification that adds sidecar proxy and traffic interception using
# Istio sidecar injection mechanism. Should be combined with an application deployment spec.
#
# Commands and flags documentation is available at
# https://istio.io/docs/reference/commands/pilot-agent/
#
apiVersion: extensions/v1beta1
kind: Deployment
spec:
  template:
    spec:
      containers:
      - name: istio-proxy
        # Replace with gcr.io/istio-testing/proxyv2:latest for the latest unstable Istio image
        image: docker.io/istio/proxyv2:1.6.5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 15090
          name: http-envoy-prom
          protocol: TCP
        args:
        - proxy
        - sidecar
        - --domain
        - $(POD_NAMESPACE).svc.cluster.local
        - --serviceCluster
        - busybox.$(POD_NAMESPACE)
        - --proxyLogLevel=warning
        - --proxyComponentLogLevel=misc:error
        - --trust-domain=cluster.local
        - --concurrency
        - "2"
        env:
        - name: ISTIO_BOOTSTRAP
          value: "/var/lib/istio/envoy/gcp_envoy_bootstrap_tmpl.json"
        - name: ISTIO_META_TRAFFICDIRECTOR_INTERCEPTION_PORT
          value: "15001"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: PROXY_CONFIG
          value: |
            {"discoveryAddress":"trafficdirector.googleapis.com:443"}
        - name: ISTIO_META_INTERCEPTION_MODE
          value: REDIRECT
        resources:
          limits:
            cpu: "2"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 1337
          runAsNonRoot: true
          runAsUser: 1337
        volumeMounts:
        - mountPath: /var/lib/istio/data
          name: istio-data
        - mountPath: /etc/istio/proxy
          name: istio-envoy
      initContainers:
      - name: istio-init
        # Replace with gcr.io/istio-testing/proxyv2:latest for the latest unstable Istio image
        image: docker.io/istio/proxyv2:1.6.5
        imagePullPolicy: IfNotPresent
        args:
        - istio-iptables
        - -p
        - "15001"
        - -u
        - "1337"
        - -m
        - REDIRECT
        - -i
        - "REPLACE_ME_VIP"
        - -x
        - ""
        - -d
        - 15090,15021,15020
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 10Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsGroup: 0
          runAsNonRoot: false
          runAsUser: 0
      securityContext:
        fsGroup: 1337
      volumes:
      - name: istio-envoy
        emptyDir:
          medium: Memory
      - name: istio-data
        emptyDir: {}
---
